Fe be serviso registracija
MatasAdmoneo/CarFans pull request #12
Opened 2023-12-04 22:29 UTC by Ech0ke

Add 3 endpoints for handling additional service in db:

Add/Update addtitional service info (will be provided from front end form)

Get additional service info by id (to fill form fields for info editing)

Get service status (for front end middleware)

Front end is implemented. It required user to submit his info and dynamically directs user in the right route/component

Sample json to use in swagger for service:

{
  "serviceName": "R2L",
  "address": "J. Basanaviciaus g. 6",
  "city": "Vilnius",
  "weeklyWorkingHours": [
    {
      "dayOfWeek": 0,
      "startTime": "8:00",
      "endTime": "17:00",
      "lunchBreakStartTime": "12:00",
      "lunchBreakEndTime": "13:00"
    }],
  "contactPhone": "+37056812276",
  "description": "assdf"
}

2023-12-05 12:49 UTC, MatasAdmoneo requested changes

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServiceWorkingDaysService.cs
> +        public void AddWorkingDaysByServiceId(Guid serviceId, List<ServiceWorkingHours> serviceWorkingHours);
`public Task AddByServiceId(Guid serviceId, List<ServiceWorkingHours> serviceWorkingHours);` 
No need to specify what you are adding because the interface name already suggests that

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServiceWorkingDaysService.cs
> +        public void RemoveWorkingDaysByServiceId(Guid serviceId);
`public Task RemoveByServiceId(Guid serviceId);`

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServicelnfoService.cs
> +        Task UpdateInfoAsync(string? serviceId, ServiceAdditionalInfoModel additionalInfo);
`Task UpdateAsync(string? serviceId, ServiceAdditionalInfoModel additionalInfo);`

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServicelnfoService.cs
> +        Task<ServiceStatus> GetServiceStatusByIdAsync(string? serviceId);
`Task<ServiceStatus> GetStatusByIdAsync(string? serviceId);`

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServiceWorkingDaysService.cs
> +using System.Threading.Tasks;
Not used

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServiceWorkingDaysService.cs
> +﻿using Cf.Domain.Aggregates.Services;
Not used

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/Interfaces/IServicelnfoService.cs
> +using Cf.Domain.Aggregates.Services;
Not used

2023-12-05 12:49 UTC, MatasAdmoneo commented on be/Cf.Application/Services/ServiceInfoServices/ServiceInfoService.cs
> +        public async Task UpdateInfoAsync(string? serviceId, ServiceAdditionalInfoModel additionalInfo)
In general this method is very crowded. I will provide some suggestions how to make it readable

2023-12-08 13:42 UTC, Ech0ke commented
Implemented fe

2023-12-09 15:28 UTC, Matas-V requested changes

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +const DayPicker = ({ formData, setFormData }: DayPickerProps) => {
Well, this component has a few bugs. For example: 
- after confirming day working hours, I am not able to edit them.
- lets say we have no working days hours confirmed and I start from the thursday putting hours, the system will track updates for sunday instead of my selected day
- When using time modal for selecting hours, so object contains selected option but FE does not show them in select
- unselecting confirmed working days also is unstable

![image](https://github.com/MatasAdmoneo/CarFans/assets/80633152/aeaf1c86-549e-4316-a0e0-2a024f5f34df)
![image](https://github.com/MatasAdmoneo/CarFans/assets/80633152/721866e8-b9ad-4d9e-8de2-9a908bf0b1f7)

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +  console.log(formData);
No need

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +    <div className="border-blue-gray-200 border-[1px] rounded-md p-1 pb-2">
If you want to use border with 1px width, so there is proper for this `border`.

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +const InfoForm = ({
Maybe `ServiceInfoForm` or `ServiceForm` is a more proper naming?

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +      const body = {
No additional data, so no need for creating `body` variable I think.

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +          json.message || response.statusText || "Unknown error occoured."
We have a const variable for unknown error `UNKNOW_ERROR_MESSAGE`.

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +          required
Remove required for all fileds as this shows default HTML message for field to be fulfilled.

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +          type="submit"
I would use fullwidth button and not sure about blue color for button, maybe we should stick with the same styling? I mean gradient variant and black color?

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/utils.ts
> +  contactPhone: string().required(),
Could add regix from our dotnet project to check if the number is correct Lithuanian number. But without message showing for this field, not sure if it is worth.

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/Stepper.tsx
> +    console.log(serviceStatus);
no need

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/Stepper.tsx
> +        {activeStep == 0 && (
Could add enum, so it would make more sense when equaling to enum type instead of number. Why not using triple equal?

2023-12-09 15:28 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +const DayPicker = ({ formData, setFormData }: DayPickerProps) => {
Also could be using standard 8-17 work hours as default, so clients as lazy as I am would not need to add every day, but it is debatable.

2023-12-11 18:23 UTC, Ech0ke commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +    <div className="border-blue-gray-200 border-[1px] rounded-md p-1 pb-2">
border-1 shows no border and border-2 border is too thick, so border-[1px] is the way to go here

2023-12-11 19:28 UTC, Ech0ke commented on fe/src/app/service/verify/components/InfoForm/InfoForm.tsx
> +          type="submit"
Full width looks ugly for me, I just swapped the color as requested

2023-12-13 08:46 UTC, Matas-V commented on fe/src/app/service/verify/components/InfoForm/DayPicker.tsx
> +    <div className="border-blue-gray-200 border-[1px] rounded-md p-1 pb-2">
the property is border not border-1.

2023-12-17 08:35 UTC, merged