about and contact pages created
MatasAdmoneo/CarFans pull request #18
Opened 2023-12-13 14:53 UTC by Saulenas69

About and contact pages created

2023-12-16 13:40 UTC, Matas-V requested changes

2023-12-16 13:40 UTC, Matas-V commented on .vscode/launch.json
> +{
I guess these files got generated as you build the whole project (FE and BE) from VS code IDE, however these files should not be deployed to the whole project, so you could add this line `.vscode` in the file `.gitignore` and those files should be ignored and not pushed to the branch.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/about/page.tsx
> +import React from 'react';
Could be removed.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/globals.css
> +
Please undo these new lines.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/about/page.tsx
> +            <Image
Heard from Aidas that there is a bug in next realted to images, so I suggest using simple `<img />` tag and just adding the src as the link of image from the internet.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/about/page.tsx
> +              className="rounded-lg transition-transform transform hover:scale-105 duration-300"
The `rounded-lg` is not needed in my opinion.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/contact/page.tsx
> +            <li>Email: <a href="mailto:info@example.com" className="text-blue-500 hover:underline">CarFans@example.com</a></li>
For me, those bullet points look ugly, we can remove them with this property `list-none` for ul tag. Also I would not mind if we aligned them in left not center like now.

![image](https://github.com/MatasAdmoneo/CarFans/assets/80633152/627d522e-3a51-4831-a2d7-9597950f3908)

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/contact/page.tsx
> +            <li>Email: <a href="mailto:info@example.com" className="text-blue-500 hover:underline">CarFans@example.com</a></li>
Also not sure if we need link for email.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/contact/page.tsx
> +          </Button>
I suggest making at least fake request sending like onClick we would clear all fields and show the toast message of succesfully send letter.

2023-12-16 13:40 UTC, Matas-V commented on fe/src/app/contact/page.tsx
> +          </Button>
Also, button styling should follow our styling across whole app, so add variant="gradient" with color black, which is by default.

2023-12-19 08:33 UTC, Ech0ke approved these changes
Fixed input styles, resolved conflicts

2023-12-19 08:33 UTC, Ech0ke commented on package-lock.json
> +{
remove this file from commit and from your local storage. It is not needed.

2023-12-19 08:33 UTC, Ech0ke commented on package.json
> +{
remove this file from commit and from your local storage. It is not needed.

2023-12-19 08:33 UTC, Ech0ke commented on .vscode/launch.json
> +{
remove this file and folder that the file lives in from commit and from your local storage. It is not needed.

2023-12-19 08:33 UTC, Ech0ke commented on .vscode/tasks.json
> +{
remove this file and folder that the file lives in from commit and from your local storage. It is not needed.

2023-12-19 08:33 UTC, merged